### ISSUE TITLE
An Idea to Implement Postinc

### ISSUE THREAD

**Issue by DoctorWkt** [EtchedPixels/Fuzix-Compiler-Kit#10]
I'm looking at postinc ++ in backend-6809.c.

For this code:

```
int x;
int y;

int main(void)
{
  y= 50;
  x= y++;  <-----
}
```

which has this subtree:

```
T_EQ v0 t10 f6 
    T_NAME v0 t10 f1 
    T_PLUSPLUS v0 t10 f2 
        T_NAME v0 t10 f1 
```

I think we can do something like this:

```
	ldd  _y+0 	; T_NAME

	pshs d		; Save the old value
	addd #1		; Do the postincrement
	std  _y+0	; Save the new value (T_NSTORE?)
	puls d		; Get the old value back

	std  _x+0	; T_EQ
```

The problem is that I don't grok backend-6809.c well enough. We effectively
need to run the T_NAME node, change T_NAME to T_NSTORE, do the push and add,
run the T_NSTORE node, then do the pull.

What's the best way to do this, Can I do:

```
	case T_PLUSPLUS:
		gen_node(n->right);
		"pshs"
		"add"
		n->right->op= T_NSTORE;
		gen_node(n->right);
		"puls"
		return 1;
```

**Comment by EtchedPixels** [comment]
I would get it generating dumb but correct code before worrying about the complexities.

It seems odd it's not already rewritten it as as an NSTORE though. That looks like a bug.

**Comment by DoctorWkt** [comment]
OK I've added the code in a pull request, and confirmed that it works for local and global ints.
