### ISSUE TITLE
reloc6800 code location?

### ISSUE THREAD

**Issue by linuxha** [EtchedPixels/Fuzix-Compiler-Kit#166]
I haven't quite figured out how to use this compiler. I'm working through the source to figure out the options so I can set the compiler correctly for the 6800 (to be used with TSC Flex). The one thing I can't quite figure out is where I get the reloc6800 code.

Any pointers?

**Comment by EtchedPixels** [comment]
I thought Flex binaries were linked at a fixed address, in which case you don't need a "reloc" tool. The reloc tool is used to generate Fuzix binaries which are relocatable.

**Comment by linuxha** [comment]
That is correct, Flex binaries are linked at a fixed address. I hadn't dug that far into fcc to see what it was doing. I just ran fcc and got the reloc6800 error. I'll create a crt0.s for Flex and work with that.

Thanks

**Comment by EtchedPixels** [comment]
Initially it's probably easier to cc -c file.c then use ld directly to get the layout you want. At the moment the front end doesn't have any platform awareness but I need to fix that anyway (eg for Z80 CP/M v Z80 Fuzix v Z80 TRSDOS etc)

**Comment by linuxha** [comment]
I used the -V to help figure out what was doing what. I need to figure out the various options so I can use them appropriately. I'll end up creating notes that can be used as documentation. I'll share :-)

**Comment by zu2** [comment]
I am trying out Fuzix C for BASICMASTER, a Japanese retro 8-bit PC. This PC does not have an OS, and programs loaded into fixed addresses are executed by calling them from BASIC. Below is the code I tried (it is in Japanese, but I think it can be read with machine translation).

https://www.zukeran.org/shin/d/2024/11/06/bm-development-environment-37/

**Comment by linuxha** [comment]
Thanks, that looks excellent! I may even read all the related posts. Translation seems to be pretty good.
:-D

**Comment by linuxha** [comment]
Should I close this one? Problem has been solved.
