### ISSUE TITLE
More tests

### ISSUE THREAD

**Issue by DoctorWkt** [EtchedPixels/Fuzix-Compiler-Kit#29]
Alan, here are a bunch more tests that I brought in from my own compiler. The `wtests` directory lives in the `test` directory. There's a `runtests` script which is 6809-specific but could easily be modified to be used with other CPUs (perhaps with an argument: `runtests 6809`).

Hope they can be of some benefit. The 6809 backend passes all the tests.
[wtests.zip](https://github.com/EtchedPixels/Fuzix-Compiler-Kit/files/14797654/wtests.zip)

**Comment by EtchedPixels** [comment]
That looks very useful indeed thanks.

Can you attach a README/LICENCE of some format so their origin etc is documented ?

**Comment by DoctorWkt** [comment]
All my tests come from https://github.com/DoctorWkt/acwj/tree/master/62_Cleanup/tests. They are currently GPL3 but I'd be happy to dual license them under the Fuzix-Compiler-Kit license. The file  `cprintf.c` comes from https://github.com/mit-pdos/xv6-public/blob/master/printf.c. It's license is here: https://github.com/mit-pdos/xv6-public?tab=License-1-ov-file#readme.

Let me know how you want the test files licensed (GPL3 or other). Then we can make a wtests/LICENCE file which describes the tests' license and the cprintf.c license.

**Comment by EtchedPixels** [comment]
Sorry been busy with other stuff
Added but seem to be short __printchar
Should that be __putchar looking at the crt0.s changes you did ?

**Comment by DoctorWkt** [comment]
On Sat, Apr 06, 2024 at 07:23:42AM -0700, EtchedPixels wrote:
>    Sorry been busy with other stuff
>    Added but seem to be short __printchar
>    Should that be __putchar looking at the crt0.s changes you did ?

Alan, I added some more I/O locations in test/emu6809.c:

void e6809_write8(unsigned addr, unsigned char val)
{
        int x;

        /* Writes to certain addresses act like system calls */
        /* 0xFEFF:  exit() with the val as the exit value */
        /* 0xFEFE:  putchar(val) */
        /* 0xFEFC/D: print out the 16-bit value as a decimal */
	...
}

and in testcrt0_6809.s:


        .export _printint
_printint:
        ldd     2,s
        std     $FEFC
        rts

        .export _putchar
_putchar:
        ldd     2,s
        stb     $FEFE
        rts

Over in https://github.com/DoctorWkt/Fuzemsys I now have 33 emulated
FUZIX system calls including fork/execve/waitpid/exit. There are about
10 important syscalls left to do, and the six or so ioctls that are
used in the FUZIX library.

I've got a few applications working, but stdio currently has compile
issues. I'll get the syscalls finished and then go look at the library.

I've done the syscall handling in a way which should be pluggable into
the other emulators. So this will help to test the compiler further.

Cheers, Warren

**Comment by DoctorWkt** [comment]
Oops, yes. It should be `_printchar` in the crt0.s file. That way it won't conflict with anything in libc. Thanks!

**Comment by EtchedPixels** [comment]
Ok fixed and merged
