### ISSUE TITLE
backend-6800.c: longs on the stack

### ISSUE THREAD

**Issue by DoctorWkt** [EtchedPixels/Fuzix-Compiler-Kit#30]
Alan, I'm trying to diagnose a problem with long arguments on the stack. I have this test program with:

```
long fred= 0x99aabbcc;

int main()
{
  func1(fred);
  return(0);
}
```

which produces the assembly code:

```
_main:
;deref r 1202 0
        ldx #_fred+0
        ldd 2,x
        ldy 0,x
        pshs d
        pshs y
        jsr _func1+0
        leas 4,s
```

So far so good. When we `jsr` to `func1()`, fred's copy is on the stack with the return address below it. Now:

```
void func1(long pos) {
  long t= pos;                           // This is the concerning code
  int *iptr= (int *)&t;
  cprintf("%x%x\n", iptr[0], iptr[1]);   // Because my cprintf() can't deal with longs
}
```

The resulting assembly is:

```
_func1:
        leas -6,s
;deref r 1205 0
        leax 2,s
        ldd 2,x
        ldy 0,x
        leax 0,s
        sty 0,x
        std 2,x
;
        tfr s,d
        std 4,s
;
        .literal
T2:
        .byte 37
        .byte 120
        .byte 37
        .byte 120
        .byte 10
        .byte 0
        .code
        ldx 4,s
        ldd 2,x
        pshs d
        ldd [6,s]
        pshs d
        ldd #T2+0
        pshs d
        jsr _cprintf+0
        leas 6,s
;
        leas 6,s
        rts
```

Perhaps a quick question to start with. Why the lots of `leax num,s`? Why not change the stack to make room for the locals and use X as a fixed frame pointer? e.g.

```
        leax 0,s      ; Make X a frame pointer. -ve offsets for locals, +ve for arguments
        leas -6,s     ; Make room for the locals
```

Anyway:

```
        leas -6,s     ; Make room for the locals
        leax 2,s      ; This should get the base address of the pos argument
        ldd 2,x       ; so we can load Y,D with the value, but 2,s is way too low now.
        ldy 0,x       ; It should be leax 8,s to clear the locals and the return address.
        leax 0,s
        sty 0,x
        std 2,x
```

So there is something wrong with the offsets against the X register for longs that are on the stack.

And (I know this would require a big backend rewrite) here is an asm version with X as a frame pointer:

```
_func1:
        tfr s,x         ; Set up X as frame pointer
        leas -6,s       ; Make room for locals
        ldd 4,x         ; Get value of pos into Y,D
        ldy 2,x
        sty -4,x        ; Save Y,D into local t
        std -2,x
;
        .literal
T2:
        .byte 37
        .byte 120
        .byte 37
        .byte 120
        .byte 10
        .byte 0
        .code
        leay -4,x       ; Get &t
        sty -6,x        ; Store in iptr
        ldd 2,y         ; Get iptr[1]
        pshs d
        ldd 0,y         ; Get iptr[0]
        pshs d
        ldd #T2+0       ; Get pointer to "%x%x\n"
        pshs d
        jsr _cprintf+0  ; Call cprintf()
        leas 6,s        ; Remove args from stack
;
        leas 6,s        ; Lose local storage
        rts             ; and return
        .export _func2
```

**Comment by DoctorWkt** [comment]
Edit: I just realised that you'd have to preserve and restore X on every `jsr` as that function would set its own frame pointer. So ignore my silly suggestion!

**Comment by DoctorWkt** [comment]
I've got a fix which passes all my existing tests and runs the test program above OK. I'll do a pull request.

**Comment by EtchedPixels** [comment]
The leax n,s stuff is because the compiler doesn't yet know how to shortcut longs. In theory it's a case of just removing the size check from the rewrites into LSTORE/LREF etc but I wanted to get things a bit more stable before doing that. Also needs a review of all the things it triggers to make sure there's nothing that breaks with float for example when it's enabled.

At that point it should write
  ldy n,s
  ldd m,s

We never actually need a frame pointer because the compiler always knows the difference between the frame and stack pointer, which means X is always usable as a working scratch pointer and unlike older 6809 compilers we will have U free as a register pointer variable one day
