### ISSUE TITLE
6809 readdir(): missing postincc

### ISSUE THREAD

**Issue by DoctorWkt** [EtchedPixels/Fuzix-Compiler-Kit#43]
Alan, looks like this line in `readdir()`:

```
return (struct __dirent *)(dir->_priv.buf + 32 * dir->_priv.next++);
```

is getting the backend to request this helper:

```
        jsr __postincc
```

Unfortunately I can't work out how to make a test program that tickles the bug. All the ones I've tried are calling `jsr __xplusplusuc` instead. Hope this helps.

Cheers, Warren

**Comment by EtchedPixels** [comment]
So it is ending up with the address on the stack as it can't load it into X without messing up D. I will take a look. I think it just needs to know that it can puls x before the jsr for those cases
