### ISSUE TITLE
Some more 6809 support routines needed

### ISSUE THREAD

**Issue by DoctorWkt** [EtchedPixels/Fuzix-Compiler-Kit#47]
Alan, with pull request #46 and with the `++` code at the end of `ddnext()` (for now) replaced with separate statements, I can now get `readdir()` to work.

Casting the next a bit wider, these libc functions need these 6809 support routines:

```
aes256.o: __xminusequc
atol.o: __xmuleql
crypt.o: __xminusequc
strtol.o: __xminusequc
tzset.o: __xmuleql
         __xminuseqc
         __xremeqc
```

I'm still too much of a 6809 newbie to know how to do these. And they are low priority, but I thought I'd mention them.
Thanks!

**Comment by EtchedPixels** [comment]
Added the ones I think we need
