### ISSUE TITLE
Building the compiler: __cast2f.c does not compile with fcc because it wants a /lib/cc1.super8

### ISSUE THREAD

**Issue by trcwm** [EtchedPixels/Fuzix-Compiler-Kit#72]
# Building the compiler

Great project! 

__cast2f.c does not compile with fcc because it wants a /lib/cc1.super8, which hasn't been built:

```
fcc -msuper8 -O -c __cast2f.c
/opt/fcc//lib/cc1.super8: No such file or directory
make[1]: *** [Makefile:27: __cast2f.o] Error 1
make[1]: Leaving directory '/storage/programming/Fuzix-Compiler-Kit/supportsuper8'
make: *** [Makefile:206: supportsuper8] Error 2
```

``cc1.super8`` also isn't in my build directory. There _is_ however a ``cc2.super8``.

git commit hash: 3fd169c215e577c6c95518ffc75144a490d12f5e

**Comment by trcwm** [comment]
I commented out the super8 from the main make file. Now the same happens with the nova target.

**Comment by EtchedPixels** [comment]
Thanks will take a look what I've broken this time

**Comment by EtchedPixels** [comment]
Did you follow the README.md and initially build with make bootstuff  then make install ?

**Comment by trcwm** [comment]
Grmbl; Sorry Alan, I didn't RTFM well enough. :cry: 
Except for a few warnings, the compiler builds now and the tests run without any complaints.
