### ISSUE TITLE
6800: support6800/divide.s can be improved.

### ISSUE THREAD

**Issue by zu2** [EtchedPixels/Fuzix-Compiler-Kit#73]
support6800/divide.s can be improved.

Inside the loop, the quotient (tmp2) is shifted left, so the least significant bit is 0. Therefore, we can simply do INC tmp2+1 to set the least significant bit.
This allows us to remove INX/DEX and LDX/STX to tmp2.
The IX register is now free, so we can use IX as a loop counter, making further improvements.
The results of the improvement are shown below.

```
div16x16:
	; TODO - should be we spot div by 0 and trap out ?
	staa @tmp1		; divisor
	stab @tmp1+1
	clra
	clrb
	stx @tmp2
	ldx	#16			; bit count
loop:
	asl @tmp2+1			; shift X left one bit at a time (dividend)
	rol @tmp2
	rolb
	rola
	subb @tmp1+1		; divisor
	sbca @tmp1
	bcc skip
	addb @tmp1+1
	adca @tmp1
	bra	skip2
skip:
	inc	@tmp2+1
skip2:
	dex
	bne loop
        ldx @tmp2
	rts

```

**Comment by EtchedPixels** [comment]
Thank you for this. I will take a look when I get a moment but it looks a lot better

**Comment by EtchedPixels** [comment]
Applied to 6800 and 6803 cases. For 6303 and 68HC11 where we use xgdx the existing code seemed best.
